version: "3.8"

services:
  postgres:
    container_name: tech-park-net-postgres
    image: library/postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: techparknet
    ports:
      - "5432:5432"
    restart: unless-stopped