version: "3.8"

services:
  postgres:
    container_name: keycloak-postgres
    image: postgres
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: keycloak_db
    ports:
      - "5444:5444"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: technopark-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: k_app
      DB_PASSWORD: 123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"